const ActionTypes = {
    SETTABLEXI:'SETTABLEXI',
    SETYEAR:'SETYEAR',
    SETTABLEYEAR:'SETTABLEYEAR',
    SETROUTE:'SETROUTE',
    SETNAV:'SETNAV',
    SETEXPOPUSHTOKEN:'SETEXPOPUSHTOKEN',
    SETNOTIFICATION:'SETNOTIFICATION',
    SETSECTIONSXI:'SETSECTIONSXI',
    SETSECTIONSXII:'SETSECTIONSXII',
    SETSUBJECTSIDS:"SETSUBJECTSIDS",
    SETINSTRUCTORS:'SETINSTRUCTORS',
    SETCURRENTTABLEXI:'SETCURRENTTABLEXI',
    SETCURRENTTABLEXII:'SETCURRENTTABLEXII'
}
export default ActionTypes